# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfetch', '0002_auto_20160806_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='rating',
            field=models.IntegerField(default=2.5),
            preserve_default=False,
        ),
    ]
