# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfetch', '0003_newsitem_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=3),
        ),
    ]
