# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfetch', '0004_auto_20160806_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
