# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsfetch', '0005_auto_20160806_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
