# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfetch', '0006_newsitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
