# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfetch', '0007_auto_20160806_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='modelrating',
            field=models.DecimalField(blank=True, decimal_places=1, default=-1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=-1, max_digits=3, null=True),
        ),
    ]
