# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfetch', '0008_auto_20160807_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='posted',
            field=models.BooleanField(default=False),
        ),
    ]
