version: '2'
services:
  db:
    image: postgres
    environment:
      - PGDATA = /var/lib/postgresql/data
    volumes:
      - data:/var/lib/postgresql/data
  rabbit:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  celery:
    build: .
    environment:
      - C_FORCE_ROOT=true
      - DATABASE_HOST=db
      - BROKER_URL=amqp://guest:guest@rabbit:5672//
    working_dir: /code
    command: bash -c "sleep 3 && celery worker -A omnesvidentes.celery -Q default -n default@%h"
    volumes:
      - ./code:/code
    depends_on:
      - db
      - rabbit
      - redis

  redis:
    image: redis

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbit
      - celery
      - flower
      - redis

  flower:
    build: .
    environment:
      - C_FORCE_ROOT=true
      - DATABASE_HOST=db
      - BROKER_URL=amqp://guest:guest@rabbit:5672//
    working_dir: /code
    command: bash -c "sleep 3 && celery -A omnesvidentes.celery -Q default flower --port=5555 --broker=amqp://guest:guest@rabbit:5672// --broker_api=http://guest:guest@rabbit:15672/api/" 
    volumes:
      - ./code:/code
    ports:
      - "5555:5555"
    links:
      - db
      - rabbit
    restart: always

volumes:
  data: {}
